[package]
name = "advent-of-code2025"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.2"
itertools = "0.12.0"
log = "0.4.20"
nom = "7.1.3"
num = "0.4.1"
petgraph = "0.6.4"
reformation = "0.5.3"
regex = "1.10.2"
simple_logger = "4.3.0"